### ISSUE TITLE
Just came here to say thank you.

### ISSUE THREAD

**Issue by fennecdjay** [fastai/fastmac#11]
I also put the link in /r/coolgithubprojects [here](https://www.reddit.com/r/coolgithubprojects/comments/ismmfd/fastmac_get_a_macos_or_linux_shell_for_free_in/).

**Comment by Silfalion** [comment]
I want to say the same. I want to cry considering how beautiful and awesome is this. Was really fond of your courses and fastai Jeremy, and had the same emotion when discovered it. Thank you both Jeremy and M Somerville. Hope this allow for ios dev sometime in the future.

**Comment by jph00** [comment]
Thanks!
