### ISSUE TITLE
Will this cause the security risk?

### ISSUE THREAD

**Issue by JasonkayZK** [fastai/fastmac#16]
This repo is awesome! ♥
But when i tried to login with ssh, there is no passwd?!
So i was wondering what if someone else also go into my github actions & using the same ssh(say: ssh rXbusP3qkYsfALDSLMQZVwG3d@sfo2.tmate.io)?
Is there any solutions for adding passwd or something?

Again, thank you for this awesome repo!♥

**Comment by jph00** [comment]
I'm not aware of any solutions, no.
